version: "3.8"

services:
  db:
    image: postgres:16-alpine
    ports:
      - 6434:6434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/mydatabase
